### ISSUE TITLE
I have some problem with generation 

### ISSUE THREAD

**Issue by tonkoshkurik** [danielauener/generator-wp-grunted-theme#2]
I have some problem with generation new theme. 
_______________

npm WARN engine grunt-phpcs@0.2.3: wanted: {"node":"0.10.x"} (current: {"node":"0.12.7","npm":"2.11.3"})
-
> node-sass@0.7.0 install /home/tonkoshkurik/work/kickstart/generator-wp-grunted-theme/new/grunt/node_modules/grunt-sass/node_modules/node-sass
> node build.js

child_process: customFds option is deprecated, use stdio instead.
make: Вход в каталог `/home/tonkoshkurik/work/kickstart/generator-wp-grunted-theme/new/grunt/node_modules/grunt-sass/node_modules/node-sass/build'
  CXX(target) Release/obj.target/binding/binding.o
In file included from ../binding.cpp:7:0:
../sass_context_wrapper.h:10:3: error: ‘uv_work_t’ does not name a type
   uv_work_t request;
   ^
../sass_context_wrapper.h:20:3: error: ‘uv_work_t’ does not name a type
   uv_work_t request;
   ^
../binding.cpp:13:20: error: variable or field ‘WorkOnContext’ declared void
 void WorkOnContext(uv_work_t* req) {
                    ^
../binding.cpp:13:20: error: ‘uv_work_t’ was not declared in this scope
../binding.cpp:13:31: error: ‘req’ was not declared in this scope
 void WorkOnContext(uv_work_t* req) {
                               ^
../binding.cpp:19:22: error: variable or field ‘MakeOldCallback’ declared void
 void MakeOldCallback(uv_work_t* req) {
                      ^
../binding.cpp:19:22: error: ‘uv_work_t’ was not declared in this scope
../binding.cpp:19:33: error: ‘req’ was not declared in this scope
 void MakeOldCallback(uv_work_t* req) {
                                 ^
make: *** [Release/obj.target/binding/binding.o] Ошибка 1
make: Выход из каталога `/home/tonkoshkurik/work/kickstart/generator-wp-grunted-theme/new/grunt/node_modules/grunt-sass/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.16.0-46-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/tonkoshkurik/work/kickstart/generator-wp-grunted-theme/new/grunt/node_modules/grunt-sass/node_modules/node-sass
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
Build failed
npm ERR! Linux 3.16.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! node-sass@0.7.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@0.7.0 install script 'node build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/tonkoshkurik/work/kickstart/generator-wp-grunted-theme/new/grunt/npm-debug.log
________________

**Comment by phauer** [comment]
I have the same problem. I'm using node 6.5.0 and npm 3.10.3.
